/**
 * Universal ERP Modules Registry
 *
 * The single source of truth for every module in the platform.
 * Tenant.enabled_modules references these codes.
 */

import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard, ShoppingCart, FileText, Receipt, FileSpreadsheet, Users, UserCircle,
  Building2, Target, Megaphone, Mail, Calendar, MessageSquare, Phone, Briefcase, Award,
  GraduationCap, Clock, FileCheck, Banknote, BarChart3, Wallet, PiggyBank, CircleDollarSign,
  Coins, Calculator, Boxes, Truck, ClipboardCheck, PackageOpen, Warehouse, ShoppingBag,
  Factory, Cog, Wrench, GitBranch, BookOpen, ShieldCheck, AlertTriangle, FlaskConical,
  Stethoscope, Plug, KeyRound, LifeBuoy, Hammer, Ticket, Folder, Globe, Settings, Shield,
  Sparkles, Plane, Bus, MapPin, Network, BadgeCheck, Layers, Webhook, Database,
  Package, Box, Tag, Bell, Files, FileSignature, Inbox, Headphones, BadgePercent, Lock,
  HardHat, Recycle, Leaf, Heart, BookOpenCheck, Store, ChartArea, RotateCw, Gauge,
  HandCoins, Trophy, Speech, ScrollText, Hourglass, Pin, History, Layout, Palette,
  PaintBucket, Code2, Workflow, Bot, Languages, FileBarChart2, FilePlus2, FileSearch,
  Building, Map, NotepadText, KanbanSquare, FileQuestion, ChartPie, GitPullRequest,
  Cuboid, SunMoon, Smartphone, Tablet, Camera, Mic, Fingerprint, Server, Cloud,
  Activity, ListTodo, ContactRound, Handshake, ChartNoAxesCombined,
} from 'lucide-react';

export type ModuleAccess = 'none' | 'read' | 'write' | 'approve' | 'admin';

export interface AppModule {
  code: string;
  name: string;
  description: string;
  pillar: ModulePillar;
  icon: LucideIcon;
  path: string;
  status: 'stable' | 'beta' | 'preview';
  permissions: Array<{ key: string; label: string; minLevel: ModuleAccess }>;
  defaultEnabled?: boolean;
  industries?: string[];
}

export type ModulePillar =
  | 'home'
  | 'sales'
  | 'marketing'
  | 'crm'
  | 'hrms'
  | 'operations'
  | 'manufacturing'
  | 'inventory'
  | 'procurement'
  | 'accounting'
  | 'projects'
  | 'quality'
  | 'assets'
  | 'customer_service'
  | 'communication'
  | 'reports'
  | 'platform'
  | 'tools';

export const pillarLabels: Record<ModulePillar, string> = {
  home: 'Home',
  sales: 'Sales',
  marketing: 'Marketing',
  crm: 'CRM',
  hrms: 'HRMS',
  operations: 'Operations',
  manufacturing: 'Manufacturing',
  inventory: 'Inventory',
  procurement: 'Procurement',
  accounting: 'Accounting',
  projects: 'Projects',
  quality: 'Quality',
  assets: 'Assets',
  customer_service: 'Customer Service',
  communication: 'Communication',
  reports: 'Reports',
  platform: 'Platform',
  tools: 'Tools',
};

export const modules: AppModule[] = [
  // ============================ HOME ============================
  {
    code: 'dashboard',
    name: 'Dashboard',
    description: 'Overview of every module enabled for the tenant.',
    pillar: 'home',
    icon: LayoutDashboard,
    path: '/app',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View dashboard', minLevel: 'read' }],
  },
  {
    code: 'inbox',
    name: 'Inbox',
    description: 'Unified inbox - messages, mentions, tasks, alerts.',
    pillar: 'home',
    icon: Inbox,
    path: '/app/inbox',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View inbox', minLevel: 'read' }],
  },
  {
    code: 'calendar',
    name: 'Calendar',
    description: 'Unified calendar across all modules.',
    pillar: 'home',
    icon: Calendar,
    path: '/app/calendar',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View calendar', minLevel: 'read' }],
  },

  // ============================ SALES ============================
  {
    code: 'sales',
    name: 'Sales',
    description: 'Customers, quotes, orders, invoices - the heart of revenue.',
    pillar: 'sales',
    icon: ShoppingCart,
    path: '/app/sales',
    status: 'stable',
    defaultEnabled: true,
    permissions: [
      { key: 'view', label: 'View sales', minLevel: 'read' },
      { key: 'edit', label: 'Edit records', minLevel: 'write' },
      { key: 'approve', label: 'Approve deals', minLevel: 'approve' },
    ],
  },
  {
    code: 'sales.customers',
    name: 'Customers',
    description: 'Customer master records with 360-degree view.',
    pillar: 'sales',
    icon: Users,
    path: '/app/sales/customers',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View customers', minLevel: 'read' }],
  },
  {
    code: 'sales.quotations',
    name: 'Quotations',
    description: 'Draft and track quotes through to acceptance.',
    pillar: 'sales',
    icon: FileText,
    path: '/app/sales/quotations',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View quotations', minLevel: 'read' }],
  },
  {
    code: 'sales.orders',
    name: 'Sales Orders',
    description: 'Convert quotes to orders and track fulfilment.',
    pillar: 'sales',
    icon: ClipboardCheck,
    path: '/app/sales/orders',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View orders', minLevel: 'read' }],
  },
  {
    code: 'sales.invoices',
    name: 'Invoices',
    description: 'Branded PDF invoices and AR tracking.',
    pillar: 'sales',
    icon: Receipt,
    path: '/app/sales/invoices',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View invoices', minLevel: 'read' }],
  },
  {
    code: 'sales.credit_notes',
    name: 'Credit Notes',
    description: 'Issue credits and apply against outstanding invoices.',
    pillar: 'sales',
    icon: FileSpreadsheet,
    path: '/app/sales/credit-notes',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View credit notes', minLevel: 'read' }],
  },
  {
    code: 'sales.returns',
    name: 'Sales Returns',
    description: 'Customer returns with inventory & financial impact.',
    pillar: 'sales',
    icon: RotateCw,
    path: '/app/sales/returns',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View returns', minLevel: 'read' }],
  },
  {
    code: 'sales.pos',
    name: 'Point of Sale',
    description: 'Touch terminal for retail, restaurant, and counter sales.',
    pillar: 'sales',
    icon: Store,
    path: '/app/pos',
    status: 'stable',
    industries: ['retail', 'hospitality'],
    permissions: [{ key: 'view', label: 'Use POS', minLevel: 'write' }],
  },
  {
    code: 'sales.recurring',
    name: 'Recurring Billing',
    description: 'Subscription invoices on a schedule.',
    pillar: 'sales',
    icon: RotateCw,
    path: '/app/sales/recurring',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View recurring', minLevel: 'read' }],
  },
  {
    code: 'sales.commissions',
    name: 'Commissions',
    description: 'Rep commission plans, accruals, and statements.',
    pillar: 'sales',
    icon: HandCoins,
    path: '/app/sales/commissions',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View commissions', minLevel: 'read' }],
  },

  // ============================ CRM ============================
  {
    code: 'crm',
    name: 'CRM',
    description: 'Leads, opportunities, accounts, and activities.',
    pillar: 'crm',
    icon: Target,
    path: '/app/crm',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View CRM', minLevel: 'read' }],
  },
  {
    code: 'crm.leads',
    name: 'Leads',
    description: 'Prospects and inbound interest.',
    pillar: 'crm',
    icon: Sparkles,
    path: '/app/crm/leads',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View leads', minLevel: 'read' }],
  },
  {
    code: 'crm.opportunities',
    name: 'Opportunities',
    description: 'Pipeline kanban with stages and forecasting.',
    pillar: 'crm',
    icon: KanbanSquare,
    path: '/app/crm/opportunities',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View opportunities', minLevel: 'read' }],
  },
  {
    code: 'crm.accounts',
    name: 'Accounts',
    description: 'Organizations you sell to.',
    pillar: 'crm',
    icon: Building2,
    path: '/app/crm/accounts',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View accounts', minLevel: 'read' }],
  },
  {
    code: 'crm.contacts',
    name: 'Contacts',
    description: 'People at customer and prospect organizations.',
    pillar: 'crm',
    icon: ContactRound,
    path: '/app/crm/contacts',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View contacts', minLevel: 'read' }],
  },
  {
    code: 'crm.activities',
    name: 'Activities',
    description: 'Calls, meetings, tasks, notes.',
    pillar: 'crm',
    icon: Activity,
    path: '/app/crm/activities',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View activities', minLevel: 'read' }],
  },
  {
    code: 'crm.forecast',
    name: 'Forecasting',
    description: 'Pipeline-based revenue forecasts.',
    pillar: 'crm',
    icon: ChartNoAxesCombined,
    path: '/app/crm/forecast',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View forecast', minLevel: 'read' }],
  },

  // ============================ MARKETING ============================
  {
    code: 'marketing',
    name: 'Marketing',
    description: 'Campaigns, segments, content, and automation.',
    pillar: 'marketing',
    icon: Megaphone,
    path: '/app/marketing',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View marketing', minLevel: 'read' }],
  },
  {
    code: 'marketing.campaigns',
    name: 'Campaigns',
    description: 'Multi-channel marketing initiatives.',
    pillar: 'marketing',
    icon: Speech,
    path: '/app/marketing/campaigns',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View campaigns', minLevel: 'read' }],
  },
  {
    code: 'marketing.segments',
    name: 'Segments',
    description: 'Dynamic queries against customers and leads.',
    pillar: 'marketing',
    icon: Layers,
    path: '/app/marketing/segments',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View segments', minLevel: 'read' }],
  },
  {
    code: 'marketing.email_templates',
    name: 'Email Templates',
    description: 'Branded templates with personalization.',
    pillar: 'marketing',
    icon: Mail,
    path: '/app/marketing/templates',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View templates', minLevel: 'read' }],
  },
  {
    code: 'marketing.landing_pages',
    name: 'Landing Pages',
    description: 'Branded campaign destinations.',
    pillar: 'marketing',
    icon: Layout,
    path: '/app/marketing/landing-pages',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View landing pages', minLevel: 'read' }],
  },
  {
    code: 'marketing.content_library',
    name: 'Content Library',
    description: 'Brochures, case studies, presentations.',
    pillar: 'marketing',
    icon: BookOpen,
    path: '/app/marketing/content',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View content library', minLevel: 'read' }],
  },
  {
    code: 'marketing.automation',
    name: 'Marketing Automation',
    description: 'Trigger-based workflows.',
    pillar: 'marketing',
    icon: Workflow,
    path: '/app/marketing/automation',
    status: 'beta',
    permissions: [{ key: 'view', label: 'View workflows', minLevel: 'read' }],
  },
  {
    code: 'marketing.loyalty',
    name: 'Loyalty Program',
    description: 'Points, tiers, referrals, gift cards.',
    pillar: 'marketing',
    icon: Trophy,
    path: '/app/marketing/loyalty',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View loyalty', minLevel: 'read' }],
  },

  // ============================ HRMS ============================
  {
    code: 'hrms',
    name: 'HR Management',
    description: 'The full employee lifecycle.',
    pillar: 'hrms',
    icon: UserCircle,
    path: '/app/hr',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View HR', minLevel: 'read' }],
  },
  {
    code: 'hrms.employees',
    name: 'Employees',
    description: 'Employee master records.',
    pillar: 'hrms',
    icon: Users,
    path: '/app/hr/employees',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View employees', minLevel: 'read' }],
  },
  {
    code: 'hrms.org_chart',
    name: 'Org Chart',
    description: 'Visual hierarchy.',
    pillar: 'hrms',
    icon: Network,
    path: '/app/hr/org-chart',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View org chart', minLevel: 'read' }],
  },
  {
    code: 'hrms.attendance',
    name: 'Attendance',
    description: 'Clock-in/out with geofencing.',
    pillar: 'hrms',
    icon: Clock,
    path: '/app/hr/attendance',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View attendance', minLevel: 'read' }],
  },
  {
    code: 'hrms.leave',
    name: 'Leave Management',
    description: 'Apply, approve, balance tracking.',
    pillar: 'hrms',
    icon: Plane,
    path: '/app/hr/leave',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View leave', minLevel: 'read' }],
  },
  {
    code: 'hrms.payroll',
    name: 'Payroll',
    description: 'Country-specific payroll runs.',
    pillar: 'hrms',
    icon: Banknote,
    path: '/app/hr/payroll',
    status: 'stable',
    permissions: [
      { key: 'view', label: 'View payroll', minLevel: 'read' },
      { key: 'approve', label: 'Approve runs', minLevel: 'approve' },
    ],
  },
  {
    code: 'hrms.expenses',
    name: 'Expenses',
    description: 'Reimbursement claims with OCR.',
    pillar: 'hrms',
    icon: Receipt,
    path: '/app/hr/expenses',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View expenses', minLevel: 'read' }],
  },
  {
    code: 'hrms.performance',
    name: 'Performance',
    description: 'Goals, reviews, calibration.',
    pillar: 'hrms',
    icon: Trophy,
    path: '/app/hr/performance',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View performance', minLevel: 'read' }],
  },
  {
    code: 'hrms.recruitment',
    name: 'Recruitment',
    description: 'Job postings, ATS, scorecards.',
    pillar: 'hrms',
    icon: Briefcase,
    path: '/app/hr/recruitment',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View recruitment', minLevel: 'read' }],
  },
  {
    code: 'hrms.onboarding',
    name: 'Onboarding',
    description: 'Configurable new-hire checklists.',
    pillar: 'hrms',
    icon: BadgeCheck,
    path: '/app/hr/onboarding',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View onboarding', minLevel: 'read' }],
  },
  {
    code: 'hrms.learning',
    name: 'Learning',
    description: 'Internal courses with quizzes.',
    pillar: 'hrms',
    icon: GraduationCap,
    path: '/app/hr/learning',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View courses', minLevel: 'read' }],
  },
  {
    code: 'hrms.compliance',
    name: 'Compliance',
    description: 'Mandatory training tracking.',
    pillar: 'hrms',
    icon: ShieldCheck,
    path: '/app/hr/compliance',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View compliance', minLevel: 'read' }],
  },

  // ============================ INVENTORY ============================
  {
    code: 'inventory',
    name: 'Inventory',
    description: 'Items, warehouses, stock levels.',
    pillar: 'inventory',
    icon: Boxes,
    path: '/app/inventory',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View inventory', minLevel: 'read' }],
  },
  {
    code: 'inventory.items',
    name: 'Items',
    description: 'Product/service master.',
    pillar: 'inventory',
    icon: Package,
    path: '/app/inventory/items',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View items', minLevel: 'read' }],
  },
  {
    code: 'inventory.warehouses',
    name: 'Warehouses',
    description: 'Physical and virtual locations.',
    pillar: 'inventory',
    icon: Warehouse,
    path: '/app/inventory/warehouses',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View warehouses', minLevel: 'read' }],
  },
  {
    code: 'inventory.stock',
    name: 'Stock Levels',
    description: 'Real-time quantities by item/location.',
    pillar: 'inventory',
    icon: PackageOpen,
    path: '/app/inventory/stock',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View stock', minLevel: 'read' }],
  },
  {
    code: 'inventory.movements',
    name: 'Stock Movements',
    description: 'Receipts, issues, transfers, adjustments.',
    pillar: 'inventory',
    icon: Truck,
    path: '/app/inventory/movements',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View movements', minLevel: 'read' }],
  },
  {
    code: 'inventory.counts',
    name: 'Stock Counts',
    description: 'Cycle, annual, and spot counts.',
    pillar: 'inventory',
    icon: ClipboardCheck,
    path: '/app/inventory/counts',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View stock counts', minLevel: 'read' }],
  },
  {
    code: 'inventory.batches',
    name: 'Batches & Serials',
    description: 'Lot tracking and serial genealogy.',
    pillar: 'inventory',
    icon: Tag,
    path: '/app/inventory/batches',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View batches', minLevel: 'read' }],
  },
  {
    code: 'inventory.wms',
    name: 'Warehouse Operations',
    description: 'Receive, putaway, pick, pack, ship.',
    pillar: 'inventory',
    icon: Cuboid,
    path: '/app/inventory/wms',
    status: 'stable',
    permissions: [{ key: 'view', label: 'Use WMS', minLevel: 'write' }],
  },

  // ============================ PROCUREMENT ============================
  {
    code: 'procurement',
    name: 'Procurement',
    description: 'Vendors, requisitions, POs, bills.',
    pillar: 'procurement',
    icon: ShoppingBag,
    path: '/app/procurement',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View procurement', minLevel: 'read' }],
  },
  {
    code: 'procurement.vendors',
    name: 'Vendors',
    description: 'Supplier master records.',
    pillar: 'procurement',
    icon: Building,
    path: '/app/procurement/vendors',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View vendors', minLevel: 'read' }],
  },
  {
    code: 'procurement.requisitions',
    name: 'Requisitions',
    description: 'Internal purchase requests with approvals.',
    pillar: 'procurement',
    icon: NotepadText,
    path: '/app/procurement/requisitions',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View requisitions', minLevel: 'read' }],
  },
  {
    code: 'procurement.rfq',
    name: 'RFQ / RFP',
    description: 'Competitive bidding with vendor portal responses.',
    pillar: 'procurement',
    icon: FileQuestion,
    path: '/app/procurement/rfq',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View RFQs', minLevel: 'read' }],
  },
  {
    code: 'procurement.orders',
    name: 'Purchase Orders',
    description: 'POs with three-way matching.',
    pillar: 'procurement',
    icon: ClipboardCheck,
    path: '/app/procurement/orders',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View POs', minLevel: 'read' }],
  },
  {
    code: 'procurement.receipts',
    name: 'Goods Receipts',
    description: 'Receive deliveries against POs.',
    pillar: 'procurement',
    icon: PackageOpen,
    path: '/app/procurement/receipts',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View receipts', minLevel: 'read' }],
  },
  {
    code: 'procurement.bills',
    name: 'Vendor Bills',
    description: 'AP with three-way matching.',
    pillar: 'procurement',
    icon: FileText,
    path: '/app/procurement/bills',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View bills', minLevel: 'read' }],
  },
  {
    code: 'procurement.scorecards',
    name: 'Vendor Scorecards',
    description: 'Performance metrics by supplier.',
    pillar: 'procurement',
    icon: BarChart3,
    path: '/app/procurement/scorecards',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View scorecards', minLevel: 'read' }],
  },

  // ============================ ACCOUNTING ============================
  {
    code: 'accounting',
    name: 'Accounting',
    description: 'Double-entry bookkeeping, full GL.',
    pillar: 'accounting',
    icon: Calculator,
    path: '/app/accounting',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View accounting', minLevel: 'read' }],
  },
  {
    code: 'accounting.coa',
    name: 'Chart of Accounts',
    description: 'Hierarchical accounts seeded per country.',
    pillar: 'accounting',
    icon: ScrollText,
    path: '/app/accounting/coa',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View COA', minLevel: 'read' }],
  },
  {
    code: 'accounting.journal',
    name: 'Journal Entries',
    description: 'Balanced debits and credits.',
    pillar: 'accounting',
    icon: FilePlus2,
    path: '/app/accounting/journal',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View journals', minLevel: 'read' }],
  },
  {
    code: 'accounting.ar',
    name: 'Accounts Receivable',
    description: 'AR aging and collections.',
    pillar: 'accounting',
    icon: CircleDollarSign,
    path: '/app/accounting/ar',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View AR', minLevel: 'read' }],
  },
  {
    code: 'accounting.ap',
    name: 'Accounts Payable',
    description: 'AP aging and payment runs.',
    pillar: 'accounting',
    icon: Coins,
    path: '/app/accounting/ap',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View AP', minLevel: 'read' }],
  },
  {
    code: 'accounting.bank',
    name: 'Banking',
    description: 'Bank reconciliation.',
    pillar: 'accounting',
    icon: Wallet,
    path: '/app/accounting/bank',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View banking', minLevel: 'read' }],
  },
  {
    code: 'accounting.fixed_assets',
    name: 'Fixed Assets',
    description: 'Capitalized assets with depreciation.',
    pillar: 'accounting',
    icon: Building2,
    path: '/app/accounting/fixed-assets',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View fixed assets', minLevel: 'read' }],
  },
  {
    code: 'accounting.budgets',
    name: 'Budgets',
    description: 'Annual budgets with variance reports.',
    pillar: 'accounting',
    icon: PiggyBank,
    path: '/app/accounting/budgets',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View budgets', minLevel: 'read' }],
  },
  {
    code: 'accounting.cashflow',
    name: 'Cash Flow',
    description: '13-week rolling forecast.',
    pillar: 'accounting',
    icon: ChartArea,
    path: '/app/accounting/cashflow',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View cashflow', minLevel: 'read' }],
  },
  {
    code: 'accounting.tax',
    name: 'Tax',
    description: 'Tax engine and statutory filings.',
    pillar: 'accounting',
    icon: ScrollText,
    path: '/app/accounting/tax',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View tax', minLevel: 'read' }],
  },
  {
    code: 'accounting.reports',
    name: 'Financial Reports',
    description: 'P&L, BS, CF, trial balance.',
    pillar: 'accounting',
    icon: FileBarChart2,
    path: '/app/accounting/reports',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View reports', minLevel: 'read' }],
  },

  // ============================ MANUFACTURING ============================
  {
    code: 'manufacturing',
    name: 'Manufacturing',
    description: 'BOMs, work orders, shop floor.',
    pillar: 'manufacturing',
    icon: Factory,
    path: '/app/manufacturing',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View manufacturing', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.bom',
    name: 'Bills of Materials',
    description: 'Multi-level BOMs.',
    pillar: 'manufacturing',
    icon: GitBranch,
    path: '/app/manufacturing/bom',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View BOMs', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.work_orders',
    name: 'Work Orders',
    description: 'Manufacturing orders through production.',
    pillar: 'manufacturing',
    icon: Hammer,
    path: '/app/manufacturing/work-orders',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View work orders', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.mrp',
    name: 'MRP',
    description: 'Materials requirements planning.',
    pillar: 'manufacturing',
    icon: Cog,
    path: '/app/manufacturing/mrp',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View MRP', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.shopfloor',
    name: 'Shop Floor',
    description: 'Operator terminal and Andon.',
    pillar: 'manufacturing',
    icon: HardHat,
    path: '/app/manufacturing/shopfloor',
    status: 'stable',
    permissions: [{ key: 'view', label: 'Use shop floor', minLevel: 'write' }],
  },
  {
    code: 'manufacturing.oee',
    name: 'OEE',
    description: 'Overall Equipment Effectiveness.',
    pillar: 'manufacturing',
    icon: Gauge,
    path: '/app/manufacturing/oee',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View OEE', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.downtime',
    name: 'Downtime',
    description: 'Track and analyze production downtime.',
    pillar: 'manufacturing',
    icon: AlertTriangle,
    path: '/app/manufacturing/downtime',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View downtime', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.routings',
    name: 'Routings',
    description: 'Operation sequences and work centers.',
    pillar: 'manufacturing',
    icon: Workflow,
    path: '/app/manufacturing/routings',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View routings', minLevel: 'read' }],
  },
  {
    code: 'manufacturing.subcontract',
    name: 'Subcontracting',
    description: 'Outsourced operations.',
    pillar: 'manufacturing',
    icon: Handshake,
    path: '/app/manufacturing/subcontract',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View subcontract', minLevel: 'read' }],
  },

  // ============================ OPERATIONS ============================
  {
    code: 'operations.logistics',
    name: 'Logistics',
    description: 'Routes, fleet, shipments.',
    pillar: 'operations',
    icon: Truck,
    path: '/app/operations/logistics',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View logistics', minLevel: 'read' }],
  },
  {
    code: 'operations.routes',
    name: 'Route Planning',
    description: 'Optimized delivery routes.',
    pillar: 'operations',
    icon: MapPin,
    path: '/app/operations/routes',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View routes', minLevel: 'read' }],
  },
  {
    code: 'operations.fleet',
    name: 'Fleet',
    description: 'Vehicle and driver management.',
    pillar: 'operations',
    icon: Bus,
    path: '/app/operations/fleet',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View fleet', minLevel: 'read' }],
  },
  {
    code: 'operations.dock',
    name: 'Dock Scheduling',
    description: 'Inbound/outbound appointments.',
    pillar: 'operations',
    icon: Warehouse,
    path: '/app/operations/dock',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View dock schedule', minLevel: 'read' }],
  },
  {
    code: 'operations.demand',
    name: 'Demand Planning',
    description: 'Statistical forecasts.',
    pillar: 'operations',
    icon: ChartArea,
    path: '/app/operations/demand',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View demand', minLevel: 'read' }],
  },
  {
    code: 'operations.sop',
    name: 'S&OP',
    description: 'Sales & Operations Planning cycles.',
    pillar: 'operations',
    icon: Calendar,
    path: '/app/operations/sop',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View S&OP', minLevel: 'read' }],
  },

  // ============================ PROJECTS ============================
  {
    code: 'projects',
    name: 'Projects',
    description: 'Tasks, milestones, time, profitability.',
    pillar: 'projects',
    icon: KanbanSquare,
    path: '/app/projects',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View projects', minLevel: 'read' }],
  },
  {
    code: 'projects.tasks',
    name: 'Tasks',
    description: 'Task lists, kanban, gantt.',
    pillar: 'projects',
    icon: ListTodo,
    path: '/app/projects/tasks',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View tasks', minLevel: 'read' }],
  },
  {
    code: 'projects.time',
    name: 'Time Tracking',
    description: 'Timer and manual entry.',
    pillar: 'projects',
    icon: Hourglass,
    path: '/app/projects/time',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View time logs', minLevel: 'read' }],
  },
  {
    code: 'projects.resources',
    name: 'Resource Planning',
    description: 'Capacity heatmaps.',
    pillar: 'projects',
    icon: Users,
    path: '/app/projects/resources',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View resources', minLevel: 'read' }],
  },

  // ============================ QUALITY ============================
  {
    code: 'quality',
    name: 'Quality',
    description: 'Inspections, NCRs, CAPAs, SPC.',
    pillar: 'quality',
    icon: ShieldCheck,
    path: '/app/quality',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View quality', minLevel: 'read' }],
  },
  {
    code: 'quality.inspections',
    name: 'Inspections',
    description: 'Incoming, in-process, final.',
    pillar: 'quality',
    icon: FlaskConical,
    path: '/app/quality/inspections',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View inspections', minLevel: 'read' }],
  },
  {
    code: 'quality.ncr',
    name: 'Non-Conformance',
    description: 'NCRs and dispositions.',
    pillar: 'quality',
    icon: AlertTriangle,
    path: '/app/quality/ncr',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View NCRs', minLevel: 'read' }],
  },
  {
    code: 'quality.capa',
    name: 'CAPA',
    description: 'Corrective & preventive actions.',
    pillar: 'quality',
    icon: FileCheck,
    path: '/app/quality/capa',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View CAPAs', minLevel: 'read' }],
  },
  {
    code: 'quality.audits',
    name: 'Audits',
    description: 'Internal, external, supplier audits.',
    pillar: 'quality',
    icon: BadgeCheck,
    path: '/app/quality/audits',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View audits', minLevel: 'read' }],
  },
  {
    code: 'quality.calibration',
    name: 'Calibration',
    description: 'Equipment calibration.',
    pillar: 'quality',
    icon: Wrench,
    path: '/app/quality/calibration',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View calibration', minLevel: 'read' }],
  },
  {
    code: 'quality.docs',
    name: 'Document Control',
    description: 'Controlled procedures and SOPs.',
    pillar: 'quality',
    icon: Files,
    path: '/app/quality/docs',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View QDocs', minLevel: 'read' }],
  },
  {
    code: 'quality.complaints',
    name: 'Customer Complaints',
    description: 'Track and investigate complaints.',
    pillar: 'quality',
    icon: AlertTriangle,
    path: '/app/quality/complaints',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View complaints', minLevel: 'read' }],
  },
  {
    code: 'quality.returns',
    name: 'RMA',
    description: 'Returns authorization.',
    pillar: 'quality',
    icon: RotateCw,
    path: '/app/quality/rma',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View RMAs', minLevel: 'read' }],
  },

  // ============================ ASSETS ============================
  {
    code: 'assets',
    name: 'Assets',
    description: 'Equipment, vehicles, IT hardware.',
    pillar: 'assets',
    icon: Boxes,
    path: '/app/assets',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View assets', minLevel: 'read' }],
  },
  {
    code: 'assets.maintenance',
    name: 'Maintenance',
    description: 'PMs and breakdowns.',
    pillar: 'assets',
    icon: Wrench,
    path: '/app/assets/maintenance',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View maintenance', minLevel: 'read' }],
  },
  {
    code: 'assets.predictive',
    name: 'Predictive Maintenance',
    description: 'AI-driven failure prediction.',
    pillar: 'assets',
    icon: Sparkles,
    path: '/app/assets/predictive',
    status: 'beta',
    permissions: [{ key: 'view', label: 'View predictions', minLevel: 'read' }],
  },
  {
    code: 'assets.spares',
    name: 'Spare Parts',
    description: 'Parts catalog and consumption.',
    pillar: 'assets',
    icon: Cog,
    path: '/app/assets/spares',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View spares', minLevel: 'read' }],
  },

  // ============================ CUSTOMER SERVICE ============================
  {
    code: 'service',
    name: 'Customer Service',
    description: 'Tickets, SLAs, knowledge base.',
    pillar: 'customer_service',
    icon: Headphones,
    path: '/app/service',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View service', minLevel: 'read' }],
  },
  {
    code: 'service.tickets',
    name: 'Tickets',
    description: 'Support ticket queue.',
    pillar: 'customer_service',
    icon: Ticket,
    path: '/app/service/tickets',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View tickets', minLevel: 'read' }],
  },
  {
    code: 'service.kb',
    name: 'Knowledge Base',
    description: 'Public and internal articles.',
    pillar: 'customer_service',
    icon: BookOpenCheck,
    path: '/app/service/kb',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View KB', minLevel: 'read' }],
  },
  {
    code: 'service.sla',
    name: 'SLA Management',
    description: 'Response and resolution targets.',
    pillar: 'customer_service',
    icon: Hourglass,
    path: '/app/service/sla',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View SLAs', minLevel: 'read' }],
  },
  {
    code: 'service.csat',
    name: 'CSAT',
    description: 'Customer satisfaction surveys.',
    pillar: 'customer_service',
    icon: Heart,
    path: '/app/service/csat',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View CSAT', minLevel: 'read' }],
  },

  // ============================ COMMUNICATION ============================
  {
    code: 'chat',
    name: 'Chat',
    description: 'Channels, DMs, threads, calls.',
    pillar: 'communication',
    icon: MessageSquare,
    path: '/app/chat',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'Use chat', minLevel: 'read' }],
  },
  {
    code: 'chat.announcements',
    name: 'Announcements',
    description: 'Broadcast to all employees.',
    pillar: 'communication',
    icon: Megaphone,
    path: '/app/chat/announcements',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View announcements', minLevel: 'read' }],
  },
  {
    code: 'chat.calls',
    name: 'Voice & Video',
    description: 'Built-in calls via WebRTC.',
    pillar: 'communication',
    icon: Phone,
    path: '/app/chat/calls',
    status: 'beta',
    permissions: [{ key: 'view', label: 'Make calls', minLevel: 'read' }],
  },

  // ============================ REPORTS ============================
  {
    code: 'reports',
    name: 'Reports',
    description: 'Built-in and custom reports.',
    pillar: 'reports',
    icon: BarChart3,
    path: '/app/reports',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View reports', minLevel: 'read' }],
  },
  {
    code: 'reports.dashboards',
    name: 'Dashboards',
    description: 'Drag-drop dashboards.',
    pillar: 'reports',
    icon: ChartPie,
    path: '/app/reports/dashboards',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View dashboards', minLevel: 'read' }],
  },
  {
    code: 'reports.builder',
    name: 'Report Builder',
    description: 'Drag-drop custom reports.',
    pillar: 'reports',
    icon: FileSpreadsheet,
    path: '/app/reports/builder',
    status: 'stable',
    permissions: [{ key: 'view', label: 'Use builder', minLevel: 'write' }],
  },
  {
    code: 'reports.ai',
    name: 'AI Insights',
    description: 'Natural-language queries.',
    pillar: 'reports',
    icon: Bot,
    path: '/app/reports/ai',
    status: 'beta',
    permissions: [{ key: 'view', label: 'Use AI insights', minLevel: 'read' }],
  },

  // ============================ TOOLS ============================
  {
    code: 'documents',
    name: 'Documents',
    description: 'File storage with e-signature.',
    pillar: 'tools',
    icon: Folder,
    path: '/app/documents',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View documents', minLevel: 'read' }],
  },
  {
    code: 'documents.esign',
    name: 'E-Signature',
    description: 'Sign documents on canvas.',
    pillar: 'tools',
    icon: FileSignature,
    path: '/app/documents/esign',
    status: 'stable',
    permissions: [{ key: 'view', label: 'Sign documents', minLevel: 'read' }],
  },
  {
    code: 'workflow',
    name: 'Workflows',
    description: 'Approval chains and automations.',
    pillar: 'tools',
    icon: Workflow,
    path: '/app/workflow',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View workflows', minLevel: 'read' }],
  },
  {
    code: 'ai',
    name: 'AI Assistant',
    description: 'OpenRouter-powered AI features.',
    pillar: 'tools',
    icon: Bot,
    path: '/app/ai',
    status: 'beta',
    permissions: [{ key: 'view', label: 'Use AI', minLevel: 'read' }],
  },
  {
    code: 'integrations',
    name: 'Integrations',
    description: 'Webhooks, plugins, third-party apps.',
    pillar: 'tools',
    icon: Plug,
    path: '/app/integrations',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View integrations', minLevel: 'read' }],
  },
  {
    code: 'audit_log',
    name: 'Audit Log',
    description: 'Immutable record of every action.',
    pillar: 'tools',
    icon: History,
    path: '/app/audit-log',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View audit log', minLevel: 'read' }],
  },

  // ============================ PLATFORM (Super Admin only) ==================
  {
    code: 'platform.tenants',
    name: 'Tenants',
    description: 'Manage tenants across the platform.',
    pillar: 'platform',
    icon: Building2,
    path: '/admin/tenants',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage tenants', minLevel: 'admin' }],
  },
  {
    code: 'platform.plans',
    name: 'Plans',
    description: 'Pricing plans and feature tiers.',
    pillar: 'platform',
    icon: Tag,
    path: '/admin/plans',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage plans', minLevel: 'admin' }],
  },
  {
    code: 'platform.resellers',
    name: 'Resellers',
    description: 'White-label distribution partners.',
    pillar: 'platform',
    icon: Handshake,
    path: '/admin/resellers',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage resellers', minLevel: 'admin' }],
  },
  {
    code: 'platform.themes',
    name: 'Theme Library',
    description: 'Curate the available themes.',
    pillar: 'platform',
    icon: Palette,
    path: '/admin/themes',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage themes', minLevel: 'admin' }],
  },
  {
    code: 'platform.modules',
    name: 'Modules Registry',
    description: 'Enable/disable modules globally.',
    pillar: 'platform',
    icon: Layers,
    path: '/admin/modules',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage modules', minLevel: 'admin' }],
  },
  {
    code: 'platform.ai',
    name: 'AI Configuration',
    description: 'OpenRouter key and model defaults.',
    pillar: 'platform',
    icon: Bot,
    path: '/admin/ai',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage AI', minLevel: 'admin' }],
  },
  {
    code: 'platform.security',
    name: 'Security',
    description: 'Platform-wide security settings.',
    pillar: 'platform',
    icon: Shield,
    path: '/admin/security',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage security', minLevel: 'admin' }],
  },
  {
    code: 'platform.backups',
    name: 'Backups',
    description: 'Backup schedules and restores.',
    pillar: 'platform',
    icon: Database,
    path: '/admin/backups',
    status: 'stable',
    permissions: [{ key: 'manage', label: 'Manage backups', minLevel: 'admin' }],
  },
  {
    code: 'platform.audit',
    name: 'Platform Audit',
    description: 'Cross-tenant audit trail.',
    pillar: 'platform',
    icon: History,
    path: '/admin/audit',
    status: 'stable',
    permissions: [{ key: 'view', label: 'View audit', minLevel: 'admin' }],
  },
  {
    code: 'settings',
    name: 'Settings',
    description: 'Tenant configuration and preferences.',
    pillar: 'platform',
    icon: Settings,
    path: '/app/settings',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'View settings', minLevel: 'read' }],
  },
  {
    code: 'settings.users',
    name: 'Users & Permissions',
    description: 'Invite users and manage access.',
    pillar: 'platform',
    icon: Users,
    path: '/app/settings/users',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'Manage users', minLevel: 'admin' }],
  },
  {
    code: 'settings.appearance',
    name: 'Appearance',
    description: 'Theme Studio - themes, fonts, icons.',
    pillar: 'platform',
    icon: PaintBucket,
    path: '/app/settings/appearance',
    status: 'stable',
    defaultEnabled: true,
    permissions: [{ key: 'view', label: 'Edit appearance', minLevel: 'admin' }],
  },
];

export const modulesByCode = Object.fromEntries(modules.map((m) => [m.code, m]));

export function getModule(code: string): AppModule | undefined {
  return modulesByCode[code];
}

export function modulesInPillar(pillar: ModulePillar): AppModule[] {
  return modules.filter((m) => m.pillar === pillar);
}

export function defaultEnabledModules(): string[] {
  return modules.filter((m) => m.defaultEnabled).map((m) => m.code);
}

export function moduleCount(): number {
  return modules.length;
}
